name: sortation

version: 0.0.0.0

license-file: LICENSE

executables:
  sortation:
    main: Main.hs
    source-dirs: src

    dependencies:
      - name: base
        version: ">= 4.14 && < 5"
        mixin:
          - (Prelude as BasePrelude)
          - hiding (Prelude)
      - attoparsec
      - bytestring
      - cereal
      - cereal-text
      - cereal-vector
      - containers
      - cryptohash-md5
      - cryptohash-sha1
      - digest
      - directory
      - effectful-core
      - effectful
      - exceptions
      - filepath
      - ghc-prim
      - hashable
      - hex-text
      - iso639
      - largeword
      - monad-loops
      - natural-transformation
      - optics
      - optparse-applicative
      - pretty-simple
      - stm
      - stm-chans
      - text
      - time
      - transformers-base
      - uuid
      - vector
      - vector-algorithms
      - vector-instances
      - xml-conduit

    ghc-options:
      - -fdefer-typed-holes
      - -Wall
      - -fno-warn-name-shadowing
      - -fno-warn-unticked-promoted-constructors
      - -fno-warn-orphans
      - -Wcompat
      - -Wincomplete-patterns
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
      - -O2
      - -threaded

    default-extensions:
      - GHC2021

      - RebindableSyntax
      - ImplicitPrelude

      - AllowAmbiguousTypes
      - ApplicativeDo
      - BlockArguments
      - DataKinds
      - DefaultSignatures
      - DeriveAnyClass
      - DerivingStrategies
      - DerivingVia
      - DuplicateRecordFields
      - FunctionalDependencies
      - GADTs
      - LambdaCase
      - MagicHash
      - MultiWayIf
      - NoFieldSelectors
      - NoStarIsType
      - OverloadedLabels
      - OverloadedLists
      - OverloadedRecordDot
      - OverloadedStrings
      - PartialTypeSignatures
      - PatternSynonyms
      - QuantifiedConstraints
      - QuasiQuotes
      - RecordWildCards
      - RoleAnnotations
      - TemplateHaskell
      - TypeFamilies
      - TypeFamilyDependencies
      - UndecidableInstances
      - ViewPatterns
